### PR TITLE
Let students/TAs stop builds

### PR DESCRIPTION
**Pull request by whsu00**
Adds a button to the detail page for builds, pointing to a new route that updates a build to have "Failed" status.

~~*Note: does **not** actually stop a running job! This only updates the database (not a fix for broken autograder scripts/dockers).*~~ 
EDIT: See reply!

image

### CODE REVIEW

**Comment by ajgokhale** [comment]
Add a warning/explanation about what the button actually does

**Comment by whsu00** [comment]
New features: clicking "stop build" now actually tries to remove a build from the queue, and/or send a `KeyboardInterrupt` to the worker handling the build.

*Warning: this behavior is not natively supported by Python's `threading` -- makes use of Python's C wrapper `ctypes`*

**Comment by whsu00** [comment]
image

**Review by alina-dan — APPROVED** [review]
🉑

**Pull request merged**
